version: "3.8"

services:
  gateway:
    ports:
      - 3000:80
  meetup-login:
    ports:
      - 3001:80
  meetup-scrape:
    ports:
      - 3002:80
  avatar-storage:
    volumes:
      - ./scrapes:/scrapes/
    ports:
      - 3003:80
  redis:
    image: redis
    ports:
      - 6379:6379
