version: "3.8"

services:
  meetup-login:
    build:
      context: ./services/meetup-login
    environment:
      - TWO_CAPTCHA_API_KEY
      - TWO_CAPTCHA_HOST=http://2captcha.com/
      - REDIS_URL=redis://redis
  meetup-scrape:
    build:
      context: ./services/meetup-scrape
  gateway:
    build:
      context: ./services/gateway
  redis:
    image: redis
