version: "3.8"

services:
  meetup-login:
    build:
      context: ./services/meetup-login
    environment:
      - TWO_CAPTCHA_API_KEY
      - TWO_CAPTCHA_HOST=http://2captcha.com/
      - REDIS_URL=redis://redis
    depends_on:
      - redis
  meetup-scrape:
    build:
      context: ./services/meetup-scrape
  gateway:
    build:
      context: ./services/gateway
    ports:
      - 3000:80
    depends_on:
      - meetup-login
      - meetup-scrape
  redis:
    image: redis
