version: "3.8"

services:
  gateway:
    volumes:
      - ./services/gateway/src:/app/src
    command: npm run dev
    depends_on:
      - meetup-login
      - meetup-scrape
  meetup-login:
    ports:
      - 3001:80
    volumes:
      - ./services/meetup-login/src:/app/src
    command: npm run dev
  meetup-scrape:
    ports:
      - 3002:80
    volumes:
      - ./services/meetup-scrape/src:/app/src
    command: npm run dev
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
